show_gui: true
camera_device: 1

H_min: 141
H_max: 11

S_min: 13
S_max: 255

V_min: 0
V_max: 255

min_contour_area: 200
min_contour_radius: 14
max_contour_radius: 32
min_area_ratio: 0.0

kalman_dt: 0.2
kalman_accel_noise_mag: 0.5
hungarian_dist_thres: 60.0
hungarian_max_skipped_frames: 10

detect_manager_arm_lenght: 100
detect_manager_yoffset: 400
