show_gui: true
camera_device: 1

H_min: 10
H_max: 21

S_min: 85
S_max: 255

V_min: 188
V_max: 255

min_contour_area: 800
min_contour_radius: 29
max_contour_radius: 50
min_area_ratio: 0.5

kalman_dt: 0.2
kalman_accel_noise_mag: 0.5
hungarian_dist_thres: 60.0
hungarian_max_skipped_frames: 10

detect_manager_arm_lenght: 100
detect_manager_yoffset: 400
